### PR TITLE
Add the option to route PDFs through the Hypothesis proxy

### PR DESCRIPTION
**Pull request by judell**
The title describes what I set out to do, and what's included here. 

Along the way I found some oddities, notably https://github.com/hypothesis/wp-hypothesis/commit/0d6fd00e997b4abc9c6a54f9d049045617bb501a (which is just bizarre -- a block that begins with `?>` and ends with `<?php` ??!!!) 

[Update: Apparently that is actually a thing in PHP. However now we use an explicit include instead.]

and https://github.com/hypothesis/wp-hypothesis/commit/8cb4bbb1d04012fae8a7c8bf491dc066ffd9b1f6 (it seems necessary to turn highlights off by default before offering an option to toggle them on).

Also, regarding the name change in https://github.com/judell/wp-hypothesis/commit/87a47901ad6b2f450f30c4a99ef93120b4e36055, I'm not sure how WordPress knows that the plugin's name is now `hypothesis` not `wp-hypothesis`. Because it's configured that way somewhere? Hoping @JakeHartnell can enlighten me!

[Update: Was https://github.com/hypothesis/wp-hypothesis/pull/10 was correct? With that change in place, I was unable to zip the repo and install the zip successfully to WP. I've reverted it in https://github.com/judell/wp-hypothesis/commit/8dd21bf26763014c91a9e323b1a8fd78ece2a2f8 and that seems to work, i.e. I can zip the repo, and install successfully to WP. But maybe there's something about the actual deployment that requires the change in https://github.com/hypothesis/wp-hypothesis/pull/10?]

### CODE REVIEW

**Comment by JakeHartnell** [comment]
Need to spin up a wordpress instance again to take a closer look at this. Busy today with meetings but I'll take a look soon.

**Comment by JakeHartnell** [comment]
> Also, regarding the name change in judell@87a4790, I'm not sure how WordPress knows that the plugin's name is now hypothesis not wp-hypothesis. Because it's configured that way somewhere? Hoping @JakeHartnell can enlighten me!

The plugins name is actually `hypothesis`. wp-hypothesis is just the name of this repo.

It's configured in this bit:
```php
/**
 * @package Hypothesis
 * @version 0.4.7
 */
/*
Plugin Name: Hypothesis
Plugin URI: http://hypothes.is/
Description: Hypothesis is an open platform for the collaborative evaluation of knowledge. This plugin embeds the necessary scripts in your Wordpress site to enable any user to use Hypothesis without installing any extensions.
Author: The Hypothesis Project and contributors
Version: 0.4.7
Author URI: http://hypothes.is/
*/
```
I would recommend changing it back... otherwise people are going to have problems. You probably had to change it to wp-hypothesis on your local instance because that's the name of this repo, but when people download from wordpress the folder will simply by `hypothesis`.

**Comment by judell** [comment]
OK, I think I see what's going on here. So back to this: https://github.com/judell/wp-hypothesis/commit/f2b530da0cce6e116597514ff19638c2bf6111c5.  Since we don't want to call the repo `hypothesis`, you need to rename the local `wp-hypothesis` folder to `hypothesis`, then you can zip that, upload it, and -- I have confirmed -- successfully run. 

Sound right?

**Comment by JakeHartnell** [comment]
>  Since we don't want to call the repo hypothesis, you need to rename the local wp-hypothesis folder to hypothesis, then you can zip that, upload it, and -- I have confirmed -- successfully run. 

Yes! :tada:

**Comment by judell** [comment]
OK, then I think we are good to go. Let me know when's good this week to walk through a deployment. What's your recollection of the process on their end: how long it takes, etc.?

**Comment by JakeHartnell** [comment]
> What's your recollection of the process on their end: how long it takes, etc.?

We need @BigBlueHat to add either you or me here: https://wordpress.org/plugins/hypothesis/developers/

I'm mentioned, but annoyingly that's not my account, so I can't push the code. : /

**Comment by BigBlueHat** [comment]
@JakeHartnell what? That's not you? :disappointed: What's your correct one?

@judell can you get me some wordpress.org account names for who you want added there?

**Comment by timmmmyboy** [comment]
I actually still have admin access here and had already added @judell in there awhile back (note that WordPress shows a different list for "Developers" that I think is based on who has pushed code to the repo, but the committer list is different and currently has me, @BigBlueHat, and @judell listed.

**Comment by JakeHartnell** [comment]
> @JakeHartnell what? That's not you? :disappointed: What's your correct one?

It's `jakehartnell` all lowercase. I think I didn't have an account when you originally created this, and you handled the deploys.

**Comment by BigBlueHat** [comment]
So, all 4 of use are listed in the committers list:

#### Committers

 *   BigBlueHat
 *   jakehartnell
 *   judell
 *   timmmmyboy

I'm showing as "admin" and am happy to hand that off to @judell once we get the rest of these access bits sorted.

**Comment by JakeHartnell** [comment]
> I'm showing as "admin" and am happy to hand that off to @judell once we get the rest of these access bits sorted.

Thanks @BigBlueHat!

**Pull request merged**
